### ISSUE TITLE
npm t not working

### ISSUE THREAD

**Issue by feesh96** [MegaArman/MusicXMLResearch#11]
Here's my error message:

![image](https://cloud.githubusercontent.com/assets/16885180/23142808/d8b0e02a-f78b-11e6-9124-b1f6f814b412.png)

Any ideas? I already tried uninstalling/reinstalling node.js 

I'm supposed to pass my tests before I add and commit, correct?

**Comment by galinabee** [comment]
Is eslint installed?

**Comment by feesh96** [comment]
When I deleted my work and re-pulled from the main branch today, all of my installs got erased, so I think that's it. I'm reinstalling eslint now and will provide an update soon!

**Comment by MegaArman** [comment]
"npm install" when you see one of the scripts in package.json is failing. You don't usually need to delete and clone again

**Comment by feesh96** [comment]
Yep, I did npm install eslint, npm install tape, and npm install -g faucet (experiment with the -g flag). 

Now when I try npm t, it can't find "xml2js" when it is required - `const xml2js = require("xml2js");`

![image](https://cloud.githubusercontent.com/assets/16885180/23143545/09a59848-f790-11e6-907a-8c6f5488d4fd.png)

How we added this dependency to our project? I won't delete it again, I promise :)

**Comment by MegaArman** [comment]
you should only have to run "npm install" and nothing else to install the dependencies now (including eslint)

**Comment by feesh96** [comment]
MegaArman back at it again with the efficiency! Resolves

**Comment by MegaArman** [comment]
noice
